name: cmaketest

on:
  push:
  #branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Build banking
      shell: bash
      run: |
        git submodule update -init --recursive 
        cd banking
        cmake -H. -B_build 
        cmake --build _build
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      
      - name: update &install
        run: |
          git submodule update --init
          sudo apt install lcov && sudo apt install g++-7
        shell: bash
      
      
      - name: startCov
        run: |
          mkdir _build && cd _build
          CXX=/usr/bin/g++-7 cmake -DCOVERAGE=1 ..
          cmake --build
          ./test
          lcov -t "banking" lcov.info -c -d .
          lcov --remove lcov.info '/home/runner/work/lab5/lab5/third-party/gtest/*'  lcov.info
          lcov --remove lcov.info '/usr/include/*'  lcov.info
        
        shell: bash
      
      
      - name: final
        uses: coverallsapp/github-action@master
        with: 
         github-token: ${{ secrets.github_token }}
         path-to-lcov: ./_build/lcov.info
         coveralls-endpoint: https://coveralls.io
       
     
        
