name: cov
on: 
  push:
    Build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        
        
        - name: build
          shell: bash
          run: git submodule update --init --recursive && cd banking && cmake -H. -B_build && cmake --build _build
          
        - name: update
          shell: bash
          run: git submodule update --init
          sudo apt install lcov && sudo apt install g++-7
          
        - name: cov1
          shell: bash
          run: mkdir _build && cd _build && CXX=/usr/bin/g++-7 cmake -DCOVERAGE=1 .. && cmake --build . && ./test && lcov -t "banking" -o lcov.info -c -d . && lcov --remove lcov.info '/home/runner/work/lab5/lab5/third-party/gtest/*' -o lcov.info && lcov --remove lcov.info '/usr/include/*' -o lcov.info
          
        - name: cov2
          uses: coverallsapp/github-action@master
          with: 
            github-token: ${{ secrets.github_token }}
            path-to-lcov: ./_build/lcov.info
            coveralls-endpoint: https://coveralls.info
        
